services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: Tian
      POSTGRES_PASSWORD: Modul@rdev@2024
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

  hikvision-server:
    build:
      context: ./hikvision-server
    restart: always
    env_file:
      - ./hikvision-server/.env
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  websocket-server:
    build:
      context: ./Modular/websocket-server
    restart: always
    env_file:
      - ./Modular/websocket-server/.env
    depends_on:
      - postgres
    ports:
      - "3002:3001"
    volumes:
      - ./Modular/websocket-server/logs:/app/logs
      - ./Modular/websocket-server/sessions:/app/sessions

  modular:
    build:
      context: ./Modular
    restart: always
    depends_on:
      - postgres
      - websocket-server
    ports:
      - "80:80"
    volumes:
      - ./Modular:/var/www/html
      - ./Uploads:/var/www/html/Uploads
      - ./hikvision-server:/var/www/hikvision-server

volumes:
  pgdata:
