-- Active: 1751521549530@@127.0.0.1@5432@modular_system
-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.account_number
(
    id serial NOT NULL,
    account_number character varying(255) COLLATE pg_catalog."default" NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT account_number_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.customers
(
    customer_id serial NOT NULL,
    company_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    account_number character varying(50) COLLATE pg_catalog."default" NOT NULL,
    client_db character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    status character varying(55) COLLATE pg_catalog."default" NOT NULL DEFAULT 'active'::character varying,
    last_login date,
    clock_server_port integer,
    CONSTRAINT customers_pkey PRIMARY KEY (customer_id),
    CONSTRAINT customers_clock_server_port_key UNIQUE (clock_server_port)
);

CREATE TABLE IF NOT EXISTS public.technician_access_log
(
    log_id serial NOT NULL,
    technician_id integer NOT NULL,
    account_number character varying(50) COLLATE pg_catalog."default" NOT NULL,
    access_token character varying(255) COLLATE pg_catalog."default" NOT NULL,
    access_time timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    ip_address character varying(45) COLLATE pg_catalog."default" NOT NULL,
    user_agent text COLLATE pg_catalog."default",
    expiration_time timestamp without time zone,
    CONSTRAINT technician_access_log_pkey PRIMARY KEY (log_id)
);

CREATE TABLE IF NOT EXISTS public.technicians
(
    id serial NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT technicians_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    two_factor_enabled boolean DEFAULT false,
    two_factor_secret character varying(32) COLLATE pg_catalog."default",
    customer_id integer,
    status character varying(50) COLLATE pg_catalog."default" DEFAULT 'active'::character varying,
    is_first_login boolean DEFAULT true,
    last_login timestamp without time zone,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.account_number
    ADD CONSTRAINT account_number_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_account_number_user
    ON public.account_number(user_id);


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT fk_users_customer FOREIGN KEY (customer_id)
    REFERENCES public.customers (customer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_users_customer_id
    ON public.users(customer_id);

INSERT INTO public.technicians (
    email,
    password,
    name,
    role,
    created_at
) VALUES (
    'tianryno01@gmail.com',
    '$2y$10$k.Q4MLA7MKDIDr/pO6F6j.1MkohOA.62.KPFaH9jzYKuVmATBUe0i',
    'Tian',
    '1',
    '2025-01-28 21:30:15.543868'
);


INSERT INTO public.customers (
    company_name,
    email,
    account_number,
    client_db,
    created_at,
    status,
    last_login,
    clock_server_port
) VALUES 
(
    'Pokenossie',
    'pokenossie@example.com',
    'ACC003',
    'db3',
    '2025-01-28 21:37:13.950026',
    'active',
    NULL,
    10000
),
(
    'pokenossie toets',
    'pokenossietoets@example.com',
    'ACC004',
    'db4',
    '2025-01-28 21:37:13.950026',
    'active',
    NULL,
    10001
);


-- Modules table
CREATE TABLE IF NOT EXISTS public.modules (
    module_id     SERIAL PRIMARY KEY,
    module_name   VARCHAR(100) UNIQUE NOT NULL, -- e.g. 'invoicing', 'payroll'
    display_name  VARCHAR(100) NOT NULL,        -- e.g. 'Invoicing System'
    base_price    NUMERIC(10, 2) DEFAULT 0.00,
    is_active     BOOLEAN DEFAULT TRUE
);

-- Customer modules link table
CREATE TABLE IF NOT EXISTS public.customer_modules (
    id                SERIAL PRIMARY KEY,
    customer_id       INT NOT NULL REFERENCES public.customers(customer_id) ON DELETE CASCADE,
    module_id         INT NOT NULL REFERENCES public.modules(module_id) ON DELETE CASCADE,
    active            BOOLEAN DEFAULT TRUE,
    trial_mode        BOOLEAN DEFAULT FALSE,
    date_enabled      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expiry_date       TIMESTAMP,
    use_custom_price  BOOLEAN DEFAULT FALSE,
    custom_price      NUMERIC(10, 2),
    UNIQUE (customer_id, module_id)
);

INSERT INTO public.modules (module_name, display_name, base_price, is_active) VALUES
    ('access_control',        'Access Control',         0.00, TRUE),
    ('accounting',            'Accounting',             0.00, TRUE),
    ('crm',                   'CRM',                    0.00, TRUE),
    ('fleet_management',      'Fleet Management',       0.00, TRUE),
    ('hr',                    'HR',                     0.00, TRUE),
    ('inventory_management',  'Inventory Management',   0.00, TRUE),
    ('invoicing',             'Invoicing',              0.00, TRUE),
    ('payroll',               'Payroll',                0.00, TRUE),
    ('support',               'Support',                0.00, TRUE),
    ('time_and_attendance',   'Time and Attendance',    0.00, TRUE),
    ('projects',              'Projects',               0.00, TRUE),
    ('documents',             'Documents',              0.00, TRUE)
ON CONFLICT (module_name) DO NOTHING;





END;